import Footer from "@/component/common/Footer";
import Header from "@/component/common/Header";
import Head from "next/head";
import { Container, Row, Col, Form, Button } from 'react-bootstrap';
import { BsArrowRight } from "react-icons/bs";
import FaqAccordion from "@/component/common/FAQ";
import { useEffect } from "react";



const TOURS = [
  {
    "title": "Grand European Adventure",
    "image": "/images/tours/1-2000x1333.jpg",
    "link": "european-adventure.html"
  },
  {
    "title": "Amazon Rainforest Expedition",
    "image": "/images/tours/2-2305x1538.jpg",
    "link": "amazonia.html"
  },
  {
    "title": "Northern Lights Expedition",
    "image": "/images/tours/aurora-borealis-sky-181624-35404-826x1239.jpg",
    "link": "northern-lights.html"
  },
  {
    "title": "Golden Triangle Discovery",
    "image": "/images/tours/4-1800x1192.jpg",
    "link": "india.html"
  },
  {
    "title": "Mystical Machu Picchu Expedition",
    "image": "/images/tours/5-1800x1202.jpg",
    "link": "peru.html"
  },
  {
    "title": "Safari Adventure in the Serengeti",
    "image": "/images/tours/6-2305x1296.jpg",
    "link": "tanzania.html"
  },
  {
    "title": "Cultural Splendors of Japan",
    "image": "/images/tours/7-1800x1198.jpg",
    "link": "japan.html"
  },
  {
    "title": "Enchanting Galápagos Expedition",
    "image": "/images/tours/7-1.webp",
    "link": "ecuador.html"
  },
  {
    "title": "African Safari Adventure: Kruger to Victoria Falls",
    "image": "/images/tours/9-6452x4301.jpg",
    "link": "africa.html"
  },
  {
    "title": "Ancient Wonders of Egypt",
    "image": "/images/tours/10-1800x1200.jpg",
    "link": "egypt.html"
  }
]






export default function Home() {
useEffect(() => {
  const banner = document.getElementById("home-banner");

  const onScroll = () => {
    const offset = window.scrollY;
    banner.style.backgroundPositionY = offset * 0.5 + "px";
  };

  window.addEventListener("scroll", onScroll);
  return () => window.removeEventListener("scroll", onScroll);
}, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section id="home-banner">
        <Container fluid>

          <div>
            <h1>
              My Voyage Verse
            </h1>
            <h2>
              We have specially curated the best united tours just for you.
            </h2>
            <div className="banner-custom-btn">
              <h6 className="text-center mt-1">View all</h6>
              <span className="icon">
                <BsArrowRight />
              </span>
            </div>
          </div>


          <div className="bannerendcontent">
            <h4 className="text-white">
              Start your adventures with us.
            </h4>
            <h4 className="text-white">
              We will create your best memories.
            </h4>
          </div>
        </Container>
      </section>

      <section id="best-offer-service-section">

        <Container fluid>

          <h1>
            We offer the best service
          </h1>
          <Row className="info-block align-items-start">
            <Col xs={2} md={4} className="info-content">
              <p>01</p>
              <div className="divider-line"></div>
              <h3>Safety</h3>
              <p>We take tour planning very seriously.</p>
            </Col>

            <Col xs={1} md={4} className="info-content">
              <p>02</p>

              <div className="divider-line"></div>
              <h3>Service 24/7</h3>
              <p>We are available at any time and always ready to assist you.</p>
            </Col>

            <Col xs={9} md={4} className="info-content">
              <p>03</p>

              <div className="divider-line"></div>

              <h3>Professionals</h3>
              <p>You will be guided by truly professional guides.</p>
            </Col>
          </Row>
        </Container>
      </section>


      <section id="tours">

        <Container fluid>
          <Row>
            {TOURS.map((item, index) => {

              return (

                <Col xs={12} md={6}
                >
                  <div
                    className="item-img"
                  >

                    <img src={item.image} className="tours-img" />
                    <span className="icon icon-position">
                      <BsArrowRight />
                    </span>
                  </div>
                  <h2 className="m-4">{item.title}</h2>

                </Col>
              )
            })}
          </Row>
        </Container>
      </section>


      <section class="organized-adventure">
        <div class="container-fluid">
          <div class="content">
            <Col xs={10} md={6}>
              <h1>Organized Adventures: <br />What do they entail?</h1>
              <p>An extended journey skillfully arranged by a reliable operator — handling logistics, meals, experiences, and accompanied by welcoming guides.</p>
              <p>Simply select your desired adventure, pack your bags, and embark on your journey worry-free.</p>
            </Col>
          </div>
        </div>
      </section>

      <section>
        <FaqAccordion />
      </section>
      <section>

        <Container fluid className="newsletter-section py-5">
          <Row>
            {/* Left Column - Text */}
            <Col md={6} className="">
              <h1 className="fw-bold">Subscribe to Our Newsletter</h1>
              <p>
                Unlock savings of up to 50% on tours! Receive exclusive email offers
                reserved for members only.
              </p>
            </Col>

            {/* Right Column - Form */}
            <Col md={6} className="newsletter-form">
              <Form>
                <Form.Group controlId="firstName" className="mb-3">
                  <Form.Label>First name*</Form.Label>
                  <Form.Control type="text" placeholder="Enter first name" />
                </Form.Group>

                <Form.Group controlId="lastName" className="mb-3">
                  <Form.Label>Last name*</Form.Label>
                  <Form.Control type="text" placeholder="Enter last name" />
                </Form.Group>

                <Form.Group controlId="phone" className="mb-3">
                  <Form.Label>Phone number*</Form.Label>
                  <Form.Control type="text" placeholder="Enter phone number" />
                </Form.Group>

                <Form.Group controlId="email" className="mb-3">
                  <Form.Label>Email*</Form.Label>
                  <Form.Control type="email" placeholder="Enter email" />
                </Form.Group>

                <Form.Group controlId="country" className="mb-3">
                  <Form.Label>Country</Form.Label>
                  <Form.Control type="text" placeholder="Enter country" />
                </Form.Group>

                <Form.Group controlId="address" className="mb-4">
                  <Form.Label>Full address</Form.Label>
                  <Form.Control type="text" placeholder="Enter full address" />
                </Form.Group>

                {/* Custom Subscribe Button */}
                <div className="d-flex align-items-center">
                  <div className="subscribe-btn">
                    <span>Subscribe</span>
                    <div className="arrow-circle">
                      <span>→</span>
                    </div>
                  </div>
                </div>

              </Form>
            </Col>
          </Row>
        </Container>
      </section>

      <section>
        <Container fluid className="px-5">
          <Row>
            <Col md={9}>
              <div>
                <h1>
                  Contact Us
                </h1>
                <p>if you have any questions</p>
              </div>
                <div>
                <h5>
                 Number phone:
                </h5>
                <p>+1-888-298-1073</p>
              </div>
                <div>
                <h5>
                E-mail
                </h5>
                <p>myvoyageverse@gmail.com</p>
              </div>

                <div>
                <h5>
                  Address
                </h5>
                <p>Sherman Ave Suite 200, Palo Alto, CA 94306, US</p>
              </div>
            </Col>
            <Col md={3}>
            <img src="/images/tours/travel-items-assortment-top-view-23-2149617655-1160x773.jpg"  className="contact-us-image"/>
            </Col>
          </Row>
        </Container>
      </section>
      <Footer />
    </>
  );
}
